### PR TITLE
Add possibility to use another outputter (like Rails' logger)

### PR DESCRIPTION
**Pull request by jeromedalbert**
At work, our logs are in the Rails logger files and I only look at these (we have almost nothing on STDOUT).

This PR allows to use Priscilla with the Rails logger, or any other outputter.
### Default behavior (unchanged)

screen shot 2014-04-02 at 23 16 57
### Configured behavior

With this configuration:

``` ruby
Priscilla.configure do |c|
  c.outputter = ->(s) { Rails.logger.debug s }
  c.blank_line_before = true
  c.blank_line_after = false
end
```

The result on my `log/development.log` is

screen shot 2014-04-02 at 23 19 53

### CODE REVIEW

**Comment by Arkham** [comment]
Hey Jerome, love this feature! Will take a look at this PR later today :)

**Comment by Arkham** [comment]
Hi there! I've implemented this feature in https://github.com/Arkham/priscilla/commit/5f0c5c884c731f171f679ea9f18c34df5daf7d86, porting almost everything from your pull request :)

I didn't merge this PR right away because I didn't want to mix up the decoration of the message and its presentation, since I prefer to keep the `decorate` method and the `presenter` method as separate functionalities. Moreoever, the `blank_line_before` and `blank_line_after` options were redundant given the possibility to pass a custom presenter method. Hope it's ok :thumbsup:

Thanks a lot for your contribution!

**Comment by jeromedalbert** [comment]
Wasn't sure if you preferred the blank lines to be handled in the lambda or not. Since we're calling it presenter now, makes sense to put them in.

I use this presenter configuration `->(msg) { Rails.logger.debug "\n#{msg}" }` in order to avoid this:

screen shot 2014-04-03 at 23 46 41

Differs from the suggested README config, may be worth updating.

Cheers!

**Comment by Arkham** [comment]
Awesome, thanks a lot again :100:

**Pull request closed without merging**
